version: "3"

services:

  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  web:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - redis
      - celery-beat

  celery:
    build: .
    command: celery -A medical_toxicology_backend worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery-beat:
    build: .
    command: celery -A medical_toxicology_backend beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
